CREATE TABLE reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    court_id BIGINT NOT NULL,
    start_date_time TIMESTAMP NOT NULL,
    end_date_time TIMESTAMP NOT NULL,
    CONSTRAINT fk_court FOREIGN KEY (court_id) REFERENCES courts(id)
);

CREATE TABLE matches (
    id BIGINT PRIMARY KEY,
    player_name VARCHAR(255),
    contact_phone VARCHAR(50),
    CONSTRAINT fk_reservation FOREIGN KEY (id) REFERENCES reservations(id)
);
