CREATE TABLE app_configurations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key VARCHAR(255) NOT NULL UNIQUE,
    config_value TEXT NOT NULL,
    value_type VARCHAR(50) NOT NULL DEFAULT 'STRING',
    description VARCHAR(500)
);

-- Create index for faster lookups
CREATE INDEX idx_app_configurations_key ON app_configurations (config_key);