-- Create player_profiles table
CREATE TABLE player_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id BIGINT NOT NULL UNIQUE,
    FOREIGN KEY (person_id) REFERENCES persons(id) ON DELETE CASCADE
);
