-- Create coach_profiles table
CREATE TABLE coach_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id BIGINT NOT NULL UNIQUE,
    color_code VARCHAR(7),
    hourly_rate DECIMAL(10,2),
    FOREIGN KEY (person_id) REFERENCES persons(id) ON DELETE CASCADE
);
